### ISSUE TITLE
After hibernation, the program will become invalid and must be re-executed.

### ISSUE THREAD

**Issue by cmhdream** [dheygere/k380-fn-lock-for-windows#1]
as the title says, win10 22h2 x64

**Comment by dheygere** [comment]
Hi @cmhdream, thanks for the report.

During hibernation, the keyboard enters its standby mode and resets to its default mode => media keys. That is really annoying for those of us that prefer Fn keys, but sadly, it is the UX designed by Logitech and I do not have the knowledge to make the change permanent.

I designed the tool in this repo to be as simple/minimalist as possible. For example I refrained from adding any daemon or UI. 

Since I do not want to add any complexity, the best answer to your issue is to use the Windows Task Scheduler to run this program after every hibernation. You can refer to this post to set it all up : https://learn.microsoft.com/en-us/answers/questions/794854/run-a-program-every-time-the-computer-comes-out-of

Another solution is of course to use the tools provided by logitech (I suppose that you'd rather avoid this solution since you checked out this repo, but I don't want to assume anything) : https://support.logi.com/hc/en-us/articles/360024851333-Download-K380-Multi-Device-Bluetooth-Keyboard

**Comment by cmhdream** [comment]
[setFnKeys.zip](https://github.com/dheygere/k380-fn-lock-for-windows/files/12922515/setFnKeys.zip)
It's my setting backup. Thanks for your information & app.

Thank you very much for your detailed reply and content.
I will try it out right away to see which of these methods suits me better. Thanks again.

**Comment by andr-groth** [comment]
> Hi @cmhdream, thanks for the report.
> 
> During hibernation, the keyboard enters its standby mode and resets to its default mode => media keys. That is really annoying for those of us that prefer Fn keys, but sadly, it is the UX designed by Logitech and I do not have the knowledge to make the change permanent.
> 
> I designed the tool in this repo to be as simple/minimalist as possible. For example I refrained from adding any daemon or UI.
> 
> Since I do not want to add any complexity, the best answer to your issue is to use the Windows Task Scheduler to run this program after every hibernation. You can refer to this post to set it all up : https://learn.microsoft.com/en-us/answers/questions/794854/run-a-program-every-time-the-computer-comes-out-of
> 
> Another solution is of course to use the tools provided by logitech (I suppose that you'd rather avoid this solution since you checked out this repo, but I don't want to assume anything) : https://support.logi.com/hc/en-us/articles/360024851333-Download-K380-Multi-Device-Bluetooth-Keyboard

I was wondering if it would be possible to insert/link this information into the readme.md of the repository? That would have helped me a lot while I was struggling with the task scheduler. I had only triggered on login and unlock, but the keyboard still felt sporadically back to media mode.
